DROP TABLE IF EXISTS statistics;

CREATE TABLE IF NOT EXISTS statistics (
    id                  BIGINT                          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application         VARCHAR(255)                    NOT NULL,
    ip                  VARCHAR(255)                    NOT NULL,
    created             TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    uri                 VARCHAR(512)                    NOT NULL
);