version: '3.1'
services:
  stats-server:
    build: stats/stat-service
    image: statistic_service
    container_name: statistics_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  ewm-service:
    build: main-module
    image: main_service
    container_name: main_service_container
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=maindb
      - POSTGRES_USER=maindb
      - POSTGRES_PASSWORD=maindb
      - DB_HOST=ewm-db
      - DB_PORT=5432
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: maindb
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=maindb
      - POSTGRES_PASSWORD=maindb
